
// SET THEME
export const FETCH_SET_THEME = 'FETCH_SET_THEME'
export const RECEIVE_SET_THEME = 'RECEIVE_SET_THEME'
export const SUCCESS_SET_THEME = 'SUCCESS_SET_THEME'
export const FAILED_SET_THEME = 'FAILED_SET_THEME'